# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache:
  bundler: true
  directories:
  - "./Carthage"
osx_image: xcode9.2

# before_install:
before_script:
- "./travis/bootstrap-if-needed.sh"

script:
- bundle exec fastlane test
- pod lib lint --quick
